[jenkins]
capstone-jenkins-server ansible_host=13.235.32.29 ansible_user=ubuntu

[k8s_master]
capstone-k8s-master ansible_host=13.127.62.158 ansible_user=ubuntu

[k8s_worker]
capstone-k8s-worker-1 ansible_host=3.111.22.193 ansible_user=ubuntu

[k8s_cluster:children]
k8s_master
k8s_worker

[all:vars]
ansible_ssh_private_key_file=../Master-key.pem
ansible_ssh_common_args='-o StrictHostKeyChecking=no'