---
- name: Setup Jenkins & SonarQube Server
  hosts: jenkins
  become: yes
  tasks:
    - name: Install base tools & Java 21
      apt:
        name:
          - openjdk-21-jdk
          - maven
          - unzip
          - curl
          - git
          - ca-certificates
          - gnupg
        state: present
        update_cache: yes

    - name: Install Docker
      apt:
        name: docker.io
        state: present

    - name: Ensure Docker service is running
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Download and dearmor Jenkins official GPG key
      shell: |
        curl -fsSL https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key | gpg --dearmor --yes -o /usr/share/keyrings/jenkins-keyring.gpg
        chmod 644 /usr/share/keyrings/jenkins-keyring.gpg

    - name: Add Jenkins repository
      shell: |
        echo "deb [signed-by=/usr/share/keyrings/jenkins-keyring.gpg] https://pkg.jenkins.io/debian-stable binary/" > /etc/apt/sources.list.d/jenkins.list
        apt-get update

    - name: Install Jenkins package
      apt:
        name: jenkins
        state: present

    - name: Add ubuntu and jenkins users to docker group
      user:
        name: "{{ item }}"
        groups: docker
        append: yes
      loop:
        - ubuntu
        - jenkins

    - name: Start Jenkins service
      systemd:
        name: jenkins
        state: started
        enabled: yes

    - name: Run SonarQube container
      shell: |
        if ! docker ps -a --format '{{ '{{' }} .Names {{ '}}' }}' | grep -q '^sonarqube$'; then
          docker run -d --name sonarqube -p 9000:9000 --restart always sonarqube:lts-community
        fi